// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJxW4-2Tq7TYO7erPn7Glx15VhldaCDqE',
    appId: '1:120277221665:web:8dac39164a1ffcb7ac3e60',
    messagingSenderId: '120277221665',
    projectId: 'my-cool-chat-app',
    authDomain: 'my-cool-chat-app.firebaseapp.com',
    storageBucket: 'my-cool-chat-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDiQe7Qii51951ng0KYKWjcXTyOASo90w',
    appId: '1:120277221665:android:dccb86d411726b4aac3e60',
    messagingSenderId: '120277221665',
    projectId: 'my-cool-chat-app',
    storageBucket: 'my-cool-chat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANkfw5sTOYD2T8uincQSHLdPAjEv9rTV8',
    appId: '1:120277221665:ios:613135e03e9dfd62ac3e60',
    messagingSenderId: '120277221665',
    projectId: 'my-cool-chat-app',
    storageBucket: 'my-cool-chat-app.appspot.com',
    iosClientId: '120277221665-jj033k734nbhu385uc9tnpjbi0r7vpga.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANkfw5sTOYD2T8uincQSHLdPAjEv9rTV8',
    appId: '1:120277221665:ios:613135e03e9dfd62ac3e60',
    messagingSenderId: '120277221665',
    projectId: 'my-cool-chat-app',
    storageBucket: 'my-cool-chat-app.appspot.com',
    iosClientId: '120277221665-jj033k734nbhu385uc9tnpjbi0r7vpga.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
